In [8]:
import matplotlib.pyplot as plt
import numpy as np
import matplotlib.animation as animation
import torch

x = torch.zeros(4, 2)
print(x)
norms = torch.norm(x, p=2, dim=1, keepdim=True)
for norm in norms:
    if norm <= 0:
        print(norm)


tensor([[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]])
tensor([0.])
tensor([0.])
tensor([0.])
tensor([0.])
